### ISSUE TITLE
Far from complete

### ISSUE THREAD

**Issue by dcwbrown** [dcwbrown/dwire-debug#1]
Still to add: dump commands (ram, eeprom, flash), memory edit commands, disassemble commands, binary load and program, breakpoint, command line parameters. Most of these are prototyped and just need tidying up and simplifying.

**Comment by dcwbrown** [comment]
Done: dump commands for flash and ram, disassembly, binary load/program, ELF load/program, breakpoint and trace, and command line parameters.
Remaining: edit commands, eeprom commands.

**Comment by kadamski** [comment]
I can't find the breakpoint implementation. Did you implement it after all?

**Comment by dcwbrown** [comment]
Breakpoint has just now been implemented.

Closing this general issue in favour of specific issues.
