### ISSUE TITLE
Supported USB-TTL adaptors 

### ISSUE THREAD

**Issue by a-v-s** [dcwbrown/dwire-debug#24]
I have been testing and I found that CH340 based adaptors appear to work as well.

**Comment by dcwbrown** [comment]
Thank you André, that's a nice surprise :=).

Questions ...
- which OS was this on?
- were you using default OS drivers, and if not, what did you need to do to install some?

**Comment by a-v-s** [comment]
I am using ArchLinux (kernel version 4.12.8-2-ARCH) and I am the driver the default driver (ch341).

**Comment by dcwbrown** [comment]
Thanks André, I'll update the readme. I have also ordered a couple of CH340 usb to serial adapters from ebay and will (someday) try them on WIndows.

**Comment by kadamski** [comment]
Works for me too, in case you would like separate confirmation. On Linux, of course, but different distro. Also default driver.

**Comment by dcwbrown** [comment]
Excellent, and I can confirm that it is working on Windows 10. Nice to have an alternative to the FT232.
