### ISSUE TITLE
mega328P flash write is not performed

### ISSUE THREAD

**Issue by George-A-Chapman** [dcwbrown/dwire-debug#27]
An operator noticed that a mega328P flash write appears to successfully complete yet the flash is not written.
The hypothesis is a flash write to an AVR with BLS and greater than 8KB of flash will not occur.
Details at [http://www.avrfreaks.net/forum/debugwire-usb-uart#comment-2286266](url)

The operator created a successful patch at
[http://www.avrfreaks.net/forum/debugwire-usb-uart#comment-2287136](url)
that's copied here
[patch.txt](https://github.com/dcwbrown/dwire-debug/files/1358234/patch.txt)

Thank you for your creation and for consideration or effort for this issue.

**Comment by dcwbrown** [comment]
Thanks George. Yes, that was the issue, and it has been fixed for a while in the littlewire branch.

I've responded to the avrfreaks thread and am hoping that the littlewire branch will resolve all the issues raised there, whereupon I'll feel confident to make the master branch obsolete.
